# Generated by Django 3.2.12 on 2022-12-13 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.TextField(max_length=150)),
                ('Desc1', models.TextField(help_text='Desc./subtit. debajo del titulo principal', verbose_name='Descripcion')),
                ('SubT2', models.TextField(default='', help_text='Frase clave a recalcar entre parrafos (en negrita)', verbose_name='Sub-Titulo 2')),
                ('Desc2', models.TextField(default='', help_text='Siguiente parrafo luego de la frase recalcada.', verbose_name='Descripcion 2')),
                ('SubT3', models.TextField(default='', help_text='Nuevamente otra frase a recalcar si es necesario.', verbose_name='Sub-Titulo 3')),
                ('Desc3', models.TextField(default='', help_text='Siguiente parrafo luego de la frase', verbose_name='Descripcion 2')),
                ('Fecha_alta', models.DateField(auto_now_add=True, verbose_name='Fecha de Alta')),
                ('Img1', models.ImageField(blank=True, default='', null=True, upload_to='img_productos/', verbose_name='Imagen Principal:')),
                ('Recorte1', image_cropping.fields.ImageRatioField('Img1', '700x435', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Recorte1')),
                ('Img2', models.ImageField(blank=True, default='', null=True, upload_to='img_productos/', verbose_name='Imagen 2:')),
                ('Recorte2', image_cropping.fields.ImageRatioField('Img2', '800x500', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Recorte2')),
                ('Img3', models.ImageField(blank=True, default='', null=True, upload_to='img_productos/', verbose_name='Imagen 3:')),
                ('Recorte3', image_cropping.fields.ImageRatioField('Img3', '800x500', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Recorte3')),
                ('Img4', models.ImageField(blank=True, default='', null=True, upload_to='img_productos/', verbose_name='Imagen 4:')),
                ('Recorte4', image_cropping.fields.ImageRatioField('Img4', '800x500', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Recorte4')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('Nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(editable=False, max_length=100, verbose_name='Nombre')),
                ('email', models.TextField(blank=True, editable=False, max_length=100, verbose_name='Email')),
                ('asunto', models.TextField(blank=True, editable=False, max_length=100, verbose_name='Asunto')),
                ('mensaje', models.TextField(editable=False, max_length=400, verbose_name='Mensaje')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_alta', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('Mensaje', models.TextField(max_length=100)),
                ('Blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebONG.blog')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='Categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebONG.categoria'),
        ),
    ]
