# Generated by Django 3.2.12 on 2022-12-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebONG', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
