# Generated by Django 3.2.12 on 2022-12-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebONG', '0002_delete_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(editable=False, max_length=100, verbose_name='Nombre')),
                ('email', models.TextField(blank=True, editable=False, max_length=100, verbose_name='Email')),
                ('asunto', models.TextField(blank=True, editable=False, max_length=100, verbose_name='Asunto')),
                ('mensaje', models.TextField(editable=False, max_length=400, verbose_name='Mensaje')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
            ],
        ),
    ]
