# Generated by Django 3.2.12 on 2022-12-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebONG', '0004_usuarioextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioextra',
            name='Img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img_usuarios/', verbose_name='Perfil:'),
        ),
    ]
