# Generated by Django 3.2.12 on 2022-12-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebONG', '0005_usuarioextra_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioextra',
            name='Img',
        ),
        migrations.AlterField(
            model_name='usuarioextra',
            name='cumple',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
