# Generated by Django 3.2.12 on 2022-12-14 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebONG', '0006_auto_20221213_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Img4',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='Recorte4',
        ),
    ]
